language: python

python:
  - "3.4"

env:
  matrix:
    # - EMACS=emacs24  # This is 24.3, while magit-popup.el requires 24.4.
    - EMACS=emacs-snapshot

install:
  - if [ "$EMACS" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el;
    fi
  - if [ "$EMACS" = "emacs-snapshot" ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs-snapshot;
    fi
  - pip install snakemake

before_script:
  make .deps

script:
  make test EMACS=${EMACS}
