language: python
before_install: bash -ex .travis-ci.sh
install: make CASK="$HOME/.cask/bin/cask" EMACS="$EMACS" compile
script: make CASK="$HOME/.cask/bin/cask" EMACS="$EMACS" test
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
python:
  - "2.7"
  - "3.3"
  - "3.4"
