language: emacs-lisp
sudo: false
env:
- EVM_EMACS=emacs-24.1-travis
- EVM_EMACS=emacs-24.2-travis
- EVM_EMACS=emacs-24.3-travis
- EVM_EMACS=emacs-24.4-travis
- EVM_EMACS=emacs-24.5-travis
before_install:
- curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh
  && source ./travis.sh
- evm install "$EVM_EMACS" --use --skip
script: make clean all
notifications:
  slack:
    secure: F5LQIeAJ+q6BFpeBTyonzWD/KNKE4GsKHErKXQ7V9xDvh3uY1NF8aYwfkcT3GC8vzdcIitZjSjUkp4twC8T7E5JzaVaHiV25R1Eg7UqsvlM880tsQy7XCpFknhqm2GnBa026zWfNqYOAe1WnhN6YdxQAfklBU7OQuCCEtFEOvKk=
