language: emacs-lisp
before_install:
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go > travis.sh && source ./travis.sh
  - evm install $EVM_EMACS --use --skip
  - cask
env:
  - EVM_EMACS=emacs-24.1-bin
  - EVM_EMACS=emacs-24.2-bin
  - EVM_EMACS=emacs-24.3-bin
script:
  ./run-travis-ci.sh
