# Use Python 3.5 for our tooling
language: python
python:
  - "3.5"
sudo: false
cache:
  - pip
  - directories:
      - .cask/
env:
  global:
    # Speeds up installation of nokogiri
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    # Run unit tests against oldest supported stable, latest stable, and trunk
    - EMACS_VERSION=24.3
    - EMACS_VERSION=24.5
    - EMACS_VERSION=snapshot
    # A special job to build the manual
    - BUILD_MANUAL=yes
before_install:
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - if [[ -n $EMACS_VERSION ]]; then make -f emacs-travis.mk install_emacs; fi
  - if [[ -n $EMACS_VERSION ]]; then make -f emacs-travis.mk install_cask; fi
  - if [[ -n $EMACS_VERSION ]]; then emacs --version; fi
  # Install requirements of documentation
  - if [[ $BUILD_MANUAL == yes ]]; then pip install -r doc/requirements.txt; fi
install:
  - if [[ -n $EMACS_VERSION ]]; then make init; fi
script:
  # Lint, compile, test
  - if [[ -n $EMACS_VERSION ]]; then make compile; fi
  - if [[ -n $EMACS_VERSION ]]; then make unit; fi
  - if [[ -n $EMACS_VERSION ]]; then make specs; fi
  # Run those integration tests that we can safely run on Travis CI
  - if [[ -n $EMACS_VERSION ]]; then make LANGUAGE=emacs-lisp integ; fi
  # Build and deploy the manual
  - if [[ $BUILD_MANUAL == yes ]]; then make -C doc SPHINXOPTS=-n html; fi
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/efdc5fd9433efa7c6b80
    on_success: change
    on_failure: always
    on_start: never
matrix:
  # Finish the build even if any build with allowed failures are still running
  fast_finish: true
  allow_failures:
    # Allow the snapshot build to fail, because Emacs snapshot sometimes fails
    # to build
    - env: EMACS_VERSION=snapshot
