#!/bin/bash

unset DJANGO_SETTINGS_MODULE
unset PYTHONPATH

project=$PWD/.project
layout=$PWD/test/layout

mkdir -p $project

django-admin.py startproject project $project

for app in independent static_tag bad_src cached use_jquery rendering japanese use_backbone
do
    mkdir -p $project/$app
    django-admin.py startapp $app $project/$app
done

for i in $(find $layout -type f)
do
    target=$project/${i#$layout/}
    mkdir -p $(dirname $target)
    cp $i $target
done
