- name: install cask
  git: repo=https://github.com/cask/cask dest=~/.cask
- name: install melpa dependencies
  shell: evm use {{ item }} && cask install chdir={{ project_root }}
  with_items: "{{emacs_versions}}"
  environment: emacs_env
- name: update melpa dependencies
  shell: evm use {{ item }} && cask update chdir={{ project_root }}
  with_items: "{{emacs_versions}}"
  environment: emacs_env
