language: emacs-lisp

sudo: required

cache: apt

env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs-snapshot

matrix:
   allow_failures:
     # emacs-snapshot (emacs25) is not yet stable version.
     - env: EMACS=emacs-snapshot

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get -qq update
  - sudo apt-get -qq install ${EMACS} ${EMACS}-el
  - emacs --version

install:
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH=${PATH}:${HOME}/.cask/bin
  - cask install

script:
  - make compile test
