sudo: false
language: node_js
node_js:
- "0.10"
env:
  ## Firefox Developer Edition
  - FIREFOX_VERSION=aurora-latest
  ## Firefox Upcoming Release
  - FIREFOX_VERSION=40.0b8
  ## Firefox Releases
  - FIREFOX_VERSION=39.0
  - FIREFOX_VERSION=38.0.6
  - FIREFOX_VERSION=37.0.2
  - FIREFOX_VERSION=36.0.4

before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR"
- npm install -g npm
- npm --version

before_script:
- cd ..
- wget "https://download.mozilla.org/?product=firefox-$FIREFOX_VERSION-ssl&os=linux64&lang=en-US" -O $TRAVIS_BUILD_DIR/../firefox.tar.bz2
- tar xvf firefox.tar.bz2
- cd $TRAVIS_BUILD_DIR

script:
- export JPM_FIREFOX_BINARY=$TRAVIS_BUILD_DIR/../firefox/firefox
- export FIREFOX_BIN=$JPM_FIREFOX_BINARY
- npm run test
