language: emacs-lisp
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
install:
  - if [ "$EMACS" = 'emacs24' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq emacs24 emacs24-el emacs24-common-non-dfsg;
    fi
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq emacs-snapshot-el emacs-snapshot-gtk;
    fi
before_script:
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
  - cask
script:
  make test
notifications:
  email: false
