language: emacs-lisp

env:
  global:
    - CURL=curl -fsSkL --retry 9 --retry-delay 9
  matrix:
    - EMACS=emacs23           GUI=1
    - EMACS=emacs24           GUI=1
    - EMACS=emacs-snapshot    GUI=1
#    - EMACS=emacs-snapshot    GUI=0
#matrix:
#  allow_failures:
#    - env: EMACS=emacs-snapshot
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - make deps
  - if [ "$EMACS" = "emacs23" ]; then
      $CURL https://raw.githubusercontent.com/ohler/ert/fb3c278d/lisp/emacs-lisp/ert.el -o ert.el;
      $CURL http://elpa.gnu.org/packages/cl-lib-0.5.el -o cl-lib.el;
    fi
  - if [ "$EMACS" = "emacs24" ]; then
      sudo apt-get install -qq emacs24-el;
    fi
  - if [ "$EMACS" = "emacs-snapshot" ]; then
      sudo apt-get install -qq emacs-snapshot-el emacs-snapshot-gtk;
    fi

script:
  - $EMACS --version
  - if [ "$GUI" = "1" ]; then make testgui EMACS=${EMACS}; fi;
  - if [ "$GUI" = "0" ]; then make test EMACS=${EMACS}; fi;
  - ls -la /tmp

notifications:
  email: false
