language: clojure
sudo: no
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install emacs-24.5-travis --skip --use
  - cask
lein: lein2
env:
 - PROFILE=default
 - PROFILE=1.7
 - PROFILE=1.8
 - PROFILE=1.8-direct
script:
 - lein2 with-profiles $PROFILE test tawny.owl-test tawny.pattern-test
 - make travis
jdk:
# - openjdk7
 - oraclejdk8
notifications:
   email:
     - travis@russet.org.uk
