(source gnu)
(source melpa)

(package-file "flycheck-protobuf.el")

(depends-on "flycheck")
(depends-on "protobuf-mode")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
