pipeline:
  - name: setup
    type: command
    command: $WORKING_DIR/setup.sh
    only_if: test "$WERCKER" = "true"
  - name: Make $HOME/.ssh directory
    type: command
    command: mkdir -p $HOME/.ssh
    only_if: test "$WERCKER" = "true"
  - name: Put SSH publick key
    type: command
    command: echo "$DIGITALOCEAN_SSH_KEY_PUBLIC" > $HOME/.ssh/id_rsa.pub
    only_if: test "$WERCKER" = "true"
  - name: Put SSH private key
    type: command
    command: echo $DIGITALOCEAN_SSH_KEY_PRIVATE > $HOME/.ssh/id_rsa
    only_if: test "$WERCKER" = "true"
  - name: chmod 600 $HOME/.ssh/id_rsa
    type: command
    command: chmod 600 $HOME/.ssh/id_rsa
    only_if: test "$WERCKER" = "true"
  - name: Parallel builds each OSes
    parallel:
      - name: Build CoreOS
        type: command
        directory: $WORKING_DIR
        command: vagrant up coreos --provider=digital_ocean && ./apply-itamae-and-serverspec-to-docker.sh
        only_if: test "$WERCKER_GIT_REPOSITORY" != "serverspec"
      - name: Build CentOS 6.5
        type: command
        command: vagrant up centos65 --provider=digital_ocean && bundle exec itamae ssh --host centos65 --vagrant recipe.rb && DIGITALOCEAN=true rake spec:centos65
        directory: $WORKING_DIR
      - name: Build CentOS 7.0
        type: command
        command: vagrant up centos70 --provider=digital_ocean && bundle exec itamae ssh --host centos70 --vagrant recipe.rb && DIGITALOCEAN=true rake spec:centos70
        directory: $WORKING_DIR
      - name: Build Ubuntu 14.04
        type: command
        command: vagrant up ubuntu1404 --provider=digital_ocean && bundle exec itamae ssh --host ubuntu1404 --vagrant recipe.rb && DIGITALOCEAN=true rake spec:ubuntu1404
        directory: $WORKING_DIR
      - name: Build FreeBSD 10.1
        type: command
        command: vagrant up freebsd --provider=digital_ocean && DIGITALOCEAN=true rake spec:freebsd
        directory: $WORKING_DIR
cleanup:
  - name: vagrant destroy
    command: vagrant destroy --force
    directory: $WORKING_DIR
messenger:
  type: slack
  channel: serverspec
  url: $SLACK_WEBHOOK_URL
  icon_url: https://raw.githubusercontent.com/serverspec/serverspec-integration-test/master/walter.png
  username: Walter
