language: generic
sudo: false
env:
  - EMACS_VERSION=23.4
  - EMACS_VERSION=24.3
  - EMACS_VERSION=24.5
  - EMACS_VERSION=25-prerelease
install:
  - env
  - source test/travis-ci.sh
  - prereqs
  - emacs --version
script:
  - folded_call byte-compile pkg/*.el
  - folded_call byte-compile -Werror *.el methods/*.el
  - folded_call ert-tests
  - check-recipes -Wno-features -Wno-github -Wno-autoloads recipes/
  - check-whitespace
