sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  matrix:
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  global:
  # Turn on --use-mirrors option everywhere (even in tox):
  - PIP_USE_MIRRORS=t
  # Use Python version of the one used for running tox
  - TOXENV=py
matrix:
  allow_failures:
    - python: "3.5"
before_install:
  - pip install -q virtualenv tox
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask
  - make before-test
script:
  make travis-ci
