language: generic
sudo: required
dist: trusty

env:
  matrix:
    - EMACS=emacs24           TARGET=check
    - EMACS=emacs-snapshot    TARGET=check
    - EMACS=emacs24           TARGET=deploy-manual
  global:
    - secure: "ejv1+ub/v+Hm/23fhp4zLAHT3HiCG+YdDHai57LDe4LfEZCeGz4i/6LazbPbwm58v2YuKvMcdNshebc1s4A293ARJryPyFfW/8kEe+3hQ+cDxunNdHfqcS8SyhcDG0mrv7dqiVAtMJqB8qZb0c161KeEM8nyhC0wyQ+EZ5qJnzM="

matrix:
  allow_failures:
    - env: EMACS=emacs-snapshot    TARGET=check

install:
  - if [ "$EMACS" = "emacs24" ]; then
        sudo apt-get update &&
        sudo apt-get install --no-install-suggests --no-install-recommends --assume-yes emacs24-nox;
    fi
  - if [ "$EMACS" = "emacs-snapshot" ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get update &&
        sudo apt-get install --no-install-suggests --no-install-recommends --assume-yes emacs-snapshot;
    fi
  - if [ "$TARGET" = "deploy-manual" ]; then
        sudo apt-get update &&
        sudo apt-get install --no-install-suggests --no-install-recommends --force-yes texinfo;
    fi

script:
  make $TARGET

notifications:
  email: false
  irc: "irc.freenode.org#haskell-emacs"

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
