language: generic
sudo: false
before_install:
  - curl -L http://tamacom.com/global/global-6.5.1.tar.gz | tar xzf -
  - (cd global-6.5.1 && ./configure --prefix=/home/travis/global && make && make install)
  - export PATH=/home/travis/global/bin:$PATH
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask
env:
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
script:
  - emacs --version
  - make test
