language: emacs-lisp
sudo: required
env:
  - EMACS=emacs-snapshot
before_install:
  - sudo apt-add-repository -y ppa:ubuntu-elisp/ppa
  - sudo add-apt-repository -y ppa:ansible/ansible
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy ${EMACS}-nox
  - sudo apt-get install -qq -yy ansible
  # Bootstrap and install Cask
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="${HOME}/.cask/bin:$PATH"
install:
  - cask install
script:
  - make EMACS=$EMACS compile
  - make EMACS=$EMACS test
