language: emacs-lisp
sudo: required
before_install:
  - curl -fsSkL https://gist.githubusercontent.com/rejeep/7736123/raw > travis.sh && source ./travis.sh
  - evm install emacs-24.4-bin --skip
  - evm install $EVM_EMACS --use --skip
  - cask
env:
  - EVM_EMACS=emacs-24.3-bin
  - EVM_EMACS=emacs-24.4-bin
  - EVM_EMACS=emacs-24.5-bin
script:
  - cask exec ert-runner