language: emacs-lisp
env:
  - EMACS=emacs24
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs && sudo apt-get update -qq && sudo apt-get install -qq emacs24 emacs24-el
  - curl -fsSkL
        --max-time 10
        --retry 10
        --retry-delay 10
        https://raw.github.com/cask/cask/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
script:
  make test
