################################################################
# Setup config file ~/.mhc/config.yml
#
# Google Calendar URL for CalDAV is in the form of:
#   https://www.google.com/calendar/dav/{calendar_id}/events
#
# calendar_id:
#  for primary calendar is just your email address.
#  for others will be in the form of:
#    [long-string-of-characters]@group.calendar.google.com
#
# You can get them by clicking the down arrow next to your
# calendar at calendar.google.com and selecting 'Calendar Settings'.
# Be sure to use HTTPS in your URL, as an http address will not work.
#
# for more details about Google Calendar settings:
#   http://www.google.com/support/calendar/bin/answer.py?answer=99358
#   and click Sunbird section.
#
# Fill in the blanks indicated as *****,
# and invoke the command:
#
#   % mhc sync personal
#
# Articles in past 90 days and future 90 days in MHC
# will be mirrored to target Google Calendar.
# (Hard-coded in lib/mhc/calendar.rb for now)
# Also other articles in Google Calendar will be DELETED.
#
# Before the first try, I recommend you to
# make a new calendar on your Google Calendar,
# and backup MHC folder ~/Mai/schedule.
#
# Currently, the type of STRATEGY in SYNC_CHANNELS allows:
# + "mirror" :: mirrors MHC to Google Calendar.
# + "import" :: imports newly created (non-recurring) articles
#               on Google Calendar into MHC.
#               All articles in Google will be deleted after the import.
#
# We are planning to support the true two-way sync "sync" soon.
#
---
################################################################
GENERAL:
################################################################
  TZID: "Asia/Tokyo"
  REPOSITORY: ~/MHC

################################################################
SYNC_CHANNELS:
################################################################

- NAME: personal
  CALENDAR1: personal
  CALENDAR2: google_personal
  STRATEGY: mirror

- NAME: family
  CALENDAR1: family
  CALENDAR2: google_family
  STRATEGY: mirror

- NAME: business
  CALENDAR1: business
  CALENDAR2: google_business
  STRATEGY: mirror

# After create some articles into google_inbox with Android client,
# doing ``mhc sync inbox'' on my Mac will import the articles into my MHC.
# All articles in google_inbox will be deleted, after the import.
- NAME: inbox
  CALENDAR1: google_inbox
  CALENDAR2: master
  STRATEGY: import

################################################################
CALENDARS:
################################################################

################################################################
## MHC local

# MHC: Master calendar (default)
- &mhc_default
  NAME: master
  TYPE: mhc

# MHC: Personal calendar mirroed to my Android
- <<: *mhc_default
  NAME: personal
  FILTER: '!category:[birthday japanese]'

# MHC: Published calendar to my colleagues
- <<: *mhc_default
  NAME: business
  FILTER: '!category:[private japanese] & category:[lecture seminar conference meeting work event party trip holiday reserved task]'
  MODIFIERS:
  - hide_description
  - hide_location
  - replace_subject_by_category

# MHC: Published calendar to my family
- <<: *mhc_default
  NAME: family
  FILTER: '!category:[birthday japanese] & category:[work event party trip holiday private]'
  MODIFIERS:
  - hide_description

################################################################
## Google Calendar

# Displayname: MHC
- &google_default
  NAME: google_personal
  TYPE: caldav
  USER: *********@gmail.com
  PASSWORD: ***************
  URL: https://calendar.google.com/calendar/dav/**************************@group.calendar.google.com/events/

# Displayname: For Family
- <<: *google_default
  NAME: google_family
  URL: https://calendar.google.com/calendar/dav/**************************@group.calendar.google.com/events/

# Displayname: For Colleagues
- <<: *google_default
  NAME: google_business
  URL: https://calendar.google.com/calendar/dav/**************************@group.calendar.google.com/events/

# Displayname: Android to create articles into:
- <<: *google_default
  NAME: google_inbox
  URL: https://calendar.google.com/calendar/dav/**************************@group.calendar.google.com/events/
