site_name: "Alchemist: Elixir Tooling Integration Into Emacs"
docs_dir: doc
pages:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Server: server.md
  - Basic usage: basic_usage.md
  - Support: support.md
  - Contributing: contributing.md
theme: readthedocs