#!/bin/sh

# Emacs-IDE package creation

# Copyright (C) 2014-2015 Cédric Marie

# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

VERSION=2.1.1
rm -rf eide-$VERSION eide-$VERSION.tar

printf "\033[1mCopy source files to package directory\033[0m\n"
mkdir eide-$VERSION
cp -v src/*.el src/themes/*.el eide-$VERSION
printf "\n\033[1mCreate package archive\033[0m\n"
tar -cvf eide-$VERSION.tar eide-$VERSION
rm -rf eide-$VERSION
printf "\n\033[1;32mPackage: eide-$VERSION.tar\033[0m\n"
