#!/bin/sh

# Emacs-IDE package installation

# Copyright (C) 2014-2015 Cédric Marie

# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

VERSION=2.1.1
if [ ! -f eide-$VERSION.tar ]; then
  printf "\033[1;31meide-$VERSION.tar does not exist\033[0m\n"
  exit 1
fi

printf "\033[1mCheck Emacs version >= 24: "
emacs_major_version=`emacs --version | grep -m1 "GNU Emacs" | cut -d" " -f3 | cut -d"." -f1`
if [ "${emacs_major_version}" != "" ]; then
  if [ "${emacs_major_version}" -gt "23" ]; then
    printf "\033[1;32mOK (${emacs_major_version})\033[0m\n"
  else
    printf "\033[1;31mFAILED: Your version of Emacs (${emacs_major_version}) is not supported (version >= 24 is required)\033[0m\n"
    exit 1
  fi
else
  printf "\033[1;31mFAILED: Can't find Emacs version\033[0m\n"
  exit 1
fi

printf "\n\033[1mInstall package eide-$VERSION.tar\033[0m\n"
# --batch: don't use interactive display (implies -q: don't load ~/.emacs)
# --execute: execute package-install-file command
if emacs --batch --execute "(package-install-file \"$PWD/eide-$VERSION.tar\")" ; then
  printf "\n\033[1;32mInstallation successful (version $VERSION)\033[0m\n"
else
  printf "\n\033[1;31mInstallation failed\033[0m\n"
  exit 1
fi
