language: cpp

env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs-snapshot

compiler:
  - gcc

install:
  - if [ "$EMACS" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el;
    fi
  - if [ "$EMACS" = "emacs-snapshot" ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs-snapshot;
    fi
  - sudo apt-get install -qq make automake autoconf libpng-dev libz-dev
  - sudo apt-get install libcairo2-dev libglib2.0-dev 
  - POPPLER=poppler-0.28.1
  - wget http://poppler.freedesktop.org/$POPPLER.tar.xz
  - unxz $POPPLER.tar.xz
  - tar xf $POPPLER.tar
  - pushd $POPPLER
  - ./configure --disable-gtk-doc-html
                --disable-xpdf-headers
                --disable-poppler-qt4
                --disable-poppler-qt5
                --disable-poppler-cpp
                --disable-utils
                --enable-xpdf-headers
                && make -j4 && sudo make install
  - popd
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
  - export PATH=/home/travis/.cask/bin:$PATH
  - export LD_LIBRARY_PATH=/usr/local/lib

script:
  - make test
