language: emacs-lisp
before_install:
  - export PATH="/home/travis/.cask/bin:$PATH"
  - export PATH="/home/travis/.evm/bin:$PATH"
install:
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - cask
env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
script:
  - ./run-travis-ci.sh
notifications:
  email:
    - reximkut@gmail.com
