sudo: required
language: emacs-lisp
script:
  ./ci/run.sh
notifications:
  email:
    recipients:
      - quelpa@postmomentum.ch
      - v.schneidermann@gmail.com
    on_success: never
    on_failure: always
