language: emacs

addons:
  apt:
    sources:
      - cassou-emacs
    packages:
      - emacs24

script:
  - "emacs --batch --load latex-unicode-math-mode.el --eval '(latex-unicode-math-mode) (latex-unicode-mode)'"
