language: emacs-lisp
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pyenv
    - $HOME/.evm
    - $HOME/.cask
    - $TRAVIS_BUILD_DIR/.cask
    - $TRAVIS_BUILD_DIR/.tox
    - /usr/local/evm
env:
  global:
    - PATH=$HOME/.pyenv/bin:$HOME/.pyenv/shims:$HOME/.evm/bin:$HOME/.cask/bin:$PATH
before_install:
  # Use ansible from git unless 2.0 version will be released.
  - sudo pip install git+https://github.com/ansible/ansible
install:
  - ./travis.sh
script:
  - tox
  - ./ert.sh
after_success:
  - coveralls-merge emacs-coveralls.json
