language: emacs-lisp
env:
  - ENV_EMACS=emacs-24.1-travis
  - ENV_EMACS=emacs-24.2-travis
  - ENV_EMACS=emacs-24.3-travis
before_install:
  # Emacs
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $ENV_EMACS --use --skip
  - cask
script:
  - emacs --version
  - make