language: generic
sudo: false

env:
  matrix:
    - EVM_EMACS=emacs-24.4-travis
    - EVM_EMACS=emacs-24.5-travis
    - EVM_EMACS=emacs-git-snapshot-travis

before_install:
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - export PATH="/home/travis/.evm/bin:$PATH"
  - evm config path /tmp
  - evm install --use $EVM_EMACS

script:
  - emacs --version
  - emacs --batch --funcall batch-byte-compile plur.el
  - emacs --batch -L . --load ert --load plur-test --funcall ert-run-tests-batch-and-exit
