language: emacs-lisp
before_install:
  - sudo mkdir /usr/local/evm
  - sudo chown travis:travis /usr/local/evm
  - export PATH="/home/travis/.evm/bin:$PATH"
  - export PATH="/home/travis/.cask/bin:$PATH"
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - evm install emacs-24.3-bin --use
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python

install:
  - cask
  - evm install $EVM_EMACS --use --skip

env:
  # only emacs 24.3 seems to working for the ert tests.
  # - EVM_EMACS=emacs-23.4-bin
  # - EVM_EMACS=emacs-24.1-bin
  # - EVM_EMACS=emacs-24.2-bin
  - EVM_EMACS=emacs-24.3-bin

script:
  - emacs --version
  - make travis
