language: generic
env:
  matrix:
 #   - EMACS=xemacs21
    - EMACS=emacs23
    - EMACS=emacs24
    - EMACS=emacs-snapshot
#matrix:
#  allow_failures:
#   - env: EMACS=xemacs21
before_install:
# - if [ "$EMACS" = 'xemacs21' ]; then
#       sudo apt-get -qq update &&
#       sudo apt-get -qq -f install &&
#       sudo apt-get -qq install xemacs21-basesupport xemacs21-basesupport-el xemacs21-supportel xemacs21-support xemacs21-mulesupport-el xemacs21-mulesupport xemacs21-mule-canna-wnn xemacs21-mule-canna-wnn;
#   fi
  - if [ "$EMACS" = 'emacs23' ]; then
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs23-gtk emacs23-el;
    fi
  - if [ "$EMACS" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el texinfo;
    fi
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs-snapshot-el emacs-snapshot;
    fi        
before_script:
  - if [ ! "$EMACS" = 'emacs24' ]; then
        make downloads;
    fi
script:
#  - if [ "$EMACS" = 'xemacs21' ]; then
#        make XEMACS=$EMACS package;
#    else
#        make EMACS=$EMACS elc test;
#    fi
  - make EMACS=$EMACS elc test;
