# We should have emacs-lisp but that triggers a warning, so use what Travis uses
# anyway if you specify an invalid language.
language: ruby
sudo: false
rvm:
  - 2.3.0
cache:
  directories:
    - vendor/bundle
    - .cask/
env:
  global:
    # Speeds up installation of nokogiri
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    # Run unit tests against oldest supported stable, latest stable, and trunk
    - EMACS_VERSION=24.3
    - EMACS_VERSION=24.5 BUILD_MANUAL=yes
    - EMACS_VERSION=snapshot COMPILEFLAGS='error-on-warn'
before_install:
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
  - emacs --version
  # Install Texinfo and htmlproof when building the manual
  - if [[ $BUILD_MANUAL == yes ]]; then make -f emacs-travis.mk install_texinfo; fi
  - if [[ $BUILD_MANUAL == yes ]]; then texi2any --version; fi
install:
  - bundle install --jobs=3 --retry=3 --path vendor/bundle
  - bundle exec rake init:all
script:
  # Linting and compilation
  - bundle exec rake verify:all
  - bundle exec rake 'compile:all[$COMPILEARGS]'
  # Spec tests
  - bundle exec rake "test:specs"
  # Unit tests
  - bundle exec rake "test:unit"
  # Build the manual
  - if [[ $BUILD_MANUAL == yes ]]; then bundle exec rake doc:info test:doc deploy:manual; fi
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/efdc5fd9433efa7c6b80
    on_success: change
    on_failure: always
    on_start: never
